name: Build BOMBOM fit

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Gerar APK e AAB
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v6

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verificar Flutter
        run: flutter --version

      - name: Instalar dependências
        run: flutter pub get

      - name: Analisar projeto
        run: flutter analyze

      - name: Executar testes
        run: flutter test

      - name: Gerar APK
        run: flutter build apk --release

      - name: Gerar AAB
        run: flutter build appbundle --release

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: BOMBOM-fit-APK
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error

      - name: Salvar AAB
        uses: actions/upload-artifact@v4
        with:
          name: BOMBOM-fit-AAB
          path: build/app/outputs/bundle/release/*.aab
          if-no-files-found: error